/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author macami-3
 */
public class helicopter extends javax.swing.JFrame {

    /**
     * Creates new form helicopter
     */
    public helicopter() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        checkbox2 = new java.awt.Checkbox();
        textField1 = new java.awt.TextField();
        jSlider4 = new javax.swing.JSlider();
        jSlider5 = new javax.swing.JSlider();
        scrollbar1 = new java.awt.Scrollbar();
        scrollbar2 = new java.awt.Scrollbar();
        textField2 = new java.awt.TextField();
        JBT2 = new javax.swing.JButton();
        JBT3 = new javax.swing.JButton();
        JBT4 = new javax.swing.JButton();
        JBT5 = new javax.swing.JButton();
        JBT6 = new javax.swing.JButton();
        JBT7 = new javax.swing.JButton();
        JBT8 = new javax.swing.JButton();
        JBT9 = new javax.swing.JButton();
        JBT10 = new javax.swing.JButton();
        JBT11 = new javax.swing.JButton();
        JBT12 = new javax.swing.JButton();
        JBT1 = new javax.swing.JButton();
        JLB1 = new javax.swing.JLabel();
        JLB2 = new javax.swing.JLabel();
        JLB3 = new javax.swing.JLabel();
        JLB4 = new javax.swing.JLabel();
        JLB5 = new javax.swing.JLabel();
        JLB6 = new javax.swing.JLabel();
        JLB7 = new javax.swing.JLabel();
        JLB8 = new javax.swing.JLabel();
        JLB9 = new javax.swing.JLabel();
        JLB10 = new javax.swing.JLabel();
        JRB1 = new javax.swing.JRadioButton();
        JRB2 = new javax.swing.JRadioButton();
        JRB3 = new javax.swing.JRadioButton();
        JRB4 = new javax.swing.JRadioButton();
        JRB5 = new javax.swing.JRadioButton();
        JRB6 = new javax.swing.JRadioButton();
        JRB7 = new javax.swing.JRadioButton();
        JRB8 = new javax.swing.JRadioButton();
        JRB9 = new javax.swing.JRadioButton();
        JRB10 = new javax.swing.JRadioButton();
        JBT13 = new javax.swing.JButton();
        JBT14 = new javax.swing.JButton();
        JBT16 = new javax.swing.JButton();
        JBT17 = new javax.swing.JButton();
        JBT18 = new javax.swing.JButton();
        JBT19 = new javax.swing.JButton();
        JBT21 = new javax.swing.JButton();
        TB1 = new javax.swing.JToggleButton();
        JLB11 = new javax.swing.JLabel();
        TB2 = new javax.swing.JToggleButton();
        TB3 = new javax.swing.JToggleButton();
        TB4 = new javax.swing.JToggleButton();
        JLB14 = new javax.swing.JLabel();
        TB5 = new javax.swing.JToggleButton();
        JLB15 = new javax.swing.JLabel();
        TB6 = new javax.swing.JToggleButton();
        JLB16 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSlider6 = new javax.swing.JSlider();
        jTextField2 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        JLB12 = new javax.swing.JLabel();
        JLB13 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("fan speed");

        jLabel8.setIcon(new javax.swing.ImageIcon("/home/macami-3/NetBeansProjects/slarmy/0MtVjZN.jpg")); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        checkbox2.setBackground(new java.awt.Color(51, 0, 0));
        checkbox2.setForeground(new java.awt.Color(255, 255, 255));
        checkbox2.setLabel("TARGET CLEAR");
        getContentPane().add(checkbox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, -1));

        textField1.setBackground(new java.awt.Color(153, 51, 0));
        textField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        textField1.setEnabled(false);
        textField1.setForeground(new java.awt.Color(255, 255, 255));
        textField1.setText("type a masseg");
        textField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField1ActionPerformed(evt);
            }
        });
        getContentPane().add(textField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 460, 350, 30));

        jSlider4.setBackground(new java.awt.Color(0, 255, 255));
        jSlider4.setForeground(new java.awt.Color(255, 0, 0));
        jSlider4.setMaximum(1000);
        jSlider4.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider4StateChanged(evt);
            }
        });
        getContentPane().add(jSlider4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, -1, -1));

        jSlider5.setBackground(new java.awt.Color(0, 0, 0));
        jSlider5.setForeground(new java.awt.Color(153, 51, 0));
        jSlider5.setValue(33);
        jSlider5.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider5StateChanged(evt);
            }
        });
        getContentPane().add(jSlider5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, -1, -1));

        scrollbar1.setBackground(new java.awt.Color(153, 51, 0));
        getContentPane().add(scrollbar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, -1, 60));

        scrollbar2.setBackground(new java.awt.Color(153, 51, 0));
        getContentPane().add(scrollbar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, -1, 60));

        textField2.setBackground(new java.awt.Color(153, 51, 0));
        textField2.setEditable(false);
        textField2.setFont(new java.awt.Font("Noto Serif CJK JP", 1, 24)); // NOI18N
        textField2.setForeground(new java.awt.Color(255, 255, 255));
        textField2.setText("HELICOPTER MI24");
        textField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField2ActionPerformed(evt);
            }
        });
        getContentPane().add(textField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 250, 40));

        JBT2.setBackground(new java.awt.Color(153, 51, 0));
        JBT2.setForeground(new java.awt.Color(255, 255, 255));
        JBT2.setText("JET ENGINE");
        JBT2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBT2ActionPerformed(evt);
            }
        });
        getContentPane().add(JBT2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 70, 120, -1));

        JBT3.setBackground(new java.awt.Color(153, 51, 0));
        JBT3.setForeground(new java.awt.Color(255, 255, 255));
        JBT3.setText("LANDIN gear");
        JBT3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBT3ActionPerformed(evt);
            }
        });
        getContentPane().add(JBT3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 110, 120, -1));

        JBT4.setBackground(new java.awt.Color(153, 51, 0));
        JBT4.setForeground(new java.awt.Color(255, 255, 255));
        JBT4.setText("MR TEMP ");
        JBT4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBT4ActionPerformed(evt);
            }
        });
        getContentPane().add(JBT4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 150, 120, -1));

        JBT5.setBackground(new java.awt.Color(153, 51, 0));
        JBT5.setForeground(new java.awt.Color(255, 255, 255));
        JBT5.setText("AIR BREAK");
        JBT5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBT5ActionPerformed(evt);
            }
        });
        getContentPane().add(JBT5, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 190, 120, -1));

        JBT6.setBackground(new java.awt.Color(153, 51, 0));
        JBT6.setForeground(new java.awt.Color(255, 255, 255));
        JBT6.setText("LIGHTS");
        JBT6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBT6ActionPerformed(evt);
            }
        });
        getContentPane().add(JBT6, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 230, 120, -1));

        JBT7.setBackground(new java.awt.Color(153, 51, 0));
        JBT7.setForeground(new java.awt.Color(255, 255, 255));
        JBT7.setText("MAIN DOOR");
        JBT7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBT7ActionPerformed(evt);
            }
        });
        getContentPane().add(JBT7, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 270, 120, -1));

        JBT8.setBackground(new java.awt.Color(153, 51, 0));
        JBT8.setForeground(new java.awt.Color(255, 255, 255));
        JBT8.setText("SATELIT");
        JBT8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBT8ActionPerformed(evt);
            }
        });
        getContentPane().add(JBT8, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 310, 120, -1));

        JBT9.setBackground(new java.awt.Color(153, 51, 0));
        JBT9.setForeground(new java.awt.Color(255, 255, 255));
        JBT9.setText("MAIN ENGIN");
        JBT9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBT9ActionPerformed(evt);
            }
        });
        getContentPane().add(JBT9, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 350, 120, -1));

        JBT10.setBackground(new java.awt.Color(153, 51, 0));
        JBT10.setForeground(new java.awt.Color(255, 255, 255));
        JBT10.setText("send text");
        JBT10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBT10ActionPerformed(evt);
            }
        });
        getContentPane().add(JBT10, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 460, -1, -1));

        JBT11.setBackground(new java.awt.Color(153, 51, 0));
        JBT11.setForeground(new java.awt.Color(255, 255, 255));
        JBT11.setText("AOUTO ");
        JBT11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBT11ActionPerformed(evt);
            }
        });
        getContentPane().add(JBT11, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 390, 120, -1));

        JBT12.setBackground(new java.awt.Color(153, 51, 0));
        JBT12.setForeground(new java.awt.Color(255, 255, 255));
        JBT12.setText("GSH-23L");
        JBT12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBT12ActionPerformed(evt);
            }
        });
        getContentPane().add(JBT12, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, 110, -1));

        JBT1.setBackground(new java.awt.Color(153, 51, 0));
        JBT1.setForeground(new java.awt.Color(255, 255, 255));
        JBT1.setText("EL CLUTCH");
        JBT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBT1ActionPerformed(evt);
            }
        });
        getContentPane().add(JBT1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 30, 120, -1));

        JLB1.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        JLB1.setText("DISABLE");
        getContentPane().add(JLB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 390, 120, -1));

        JLB2.setBackground(new java.awt.Color(0, 0, 0));
        JLB2.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        JLB2.setText("OFF");
        getContentPane().add(JLB2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 30, 120, -1));

        JLB3.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        JLB3.setText("OFF");
        getContentPane().add(JLB3, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 70, 120, -1));

        JLB4.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        JLB4.setText("OFF");
        getContentPane().add(JLB4, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 110, 120, -1));

        JLB5.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        JLB5.setText("LOW");
        getContentPane().add(JLB5, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 150, 120, -1));

        JLB6.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        JLB6.setText("OFF");
        getContentPane().add(JLB6, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 190, 120, -1));

        JLB7.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        JLB7.setText("OFF");
        getContentPane().add(JLB7, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 230, 120, -1));

        JLB8.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        JLB8.setText("CLOSE");
        getContentPane().add(JLB8, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 270, 120, -1));

        JLB9.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        JLB9.setText("OFF");
        getContentPane().add(JLB9, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 310, 120, -1));

        JLB10.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        JLB10.setText("OFF ");
        getContentPane().add(JLB10, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 350, 120, -1));

        JRB1.setBackground(new java.awt.Color(153, 51, 0));
        getContentPane().add(JRB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 390, -1, -1));

        JRB2.setBackground(new java.awt.Color(153, 51, 0));
        JRB2.setForeground(new java.awt.Color(51, 255, 255));
        getContentPane().add(JRB2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 30, -1, -1));

        JRB3.setBackground(new java.awt.Color(153, 51, 0));
        JRB3.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(JRB3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 70, -1, -1));

        JRB4.setBackground(new java.awt.Color(153, 51, 0));
        JRB4.setForeground(new java.awt.Color(102, 255, 255));
        getContentPane().add(JRB4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 110, -1, -1));

        JRB5.setBackground(new java.awt.Color(153, 51, 0));
        getContentPane().add(JRB5, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 150, -1, -1));

        JRB6.setBackground(new java.awt.Color(153, 51, 0));
        getContentPane().add(JRB6, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 190, -1, -1));

        JRB7.setBackground(new java.awt.Color(153, 51, 0));
        getContentPane().add(JRB7, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 230, -1, -1));

        JRB8.setBackground(new java.awt.Color(153, 51, 0));
        getContentPane().add(JRB8, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 310, 20, -1));

        JRB9.setBackground(new java.awt.Color(153, 51, 0));
        getContentPane().add(JRB9, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 270, -1, -1));

        JRB10.setBackground(new java.awt.Color(153, 51, 0));
        getContentPane().add(JRB10, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 350, -1, -1));

        JBT13.setBackground(new java.awt.Color(153, 51, 0));
        JBT13.setForeground(new java.awt.Color(255, 255, 255));
        JBT13.setText("SHOOT");
        JBT13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBT13ActionPerformed(evt);
            }
        });
        getContentPane().add(JBT13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 110, -1));

        JBT14.setBackground(new java.awt.Color(153, 51, 0));
        JBT14.setForeground(new java.awt.Color(255, 255, 255));
        JBT14.setText("RPJ");
        JBT14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBT14ActionPerformed(evt);
            }
        });
        getContentPane().add(JBT14, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 110, -1));

        JBT16.setBackground(new java.awt.Color(153, 51, 0));
        JBT16.setForeground(new java.awt.Color(255, 255, 255));
        JBT16.setText("MISSILE");
        JBT16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBT16ActionPerformed(evt);
            }
        });
        getContentPane().add(JBT16, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 110, -1));

        JBT17.setBackground(new java.awt.Color(153, 51, 0));
        JBT17.setForeground(new java.awt.Color(255, 255, 255));
        JBT17.setText("ROTARY");
        JBT17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBT17ActionPerformed(evt);
            }
        });
        getContentPane().add(JBT17, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 110, -1));

        JBT18.setBackground(new java.awt.Color(153, 51, 0));
        JBT18.setForeground(new java.awt.Color(255, 255, 255));
        JBT18.setText("ATGMS");
        JBT18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBT18ActionPerformed(evt);
            }
        });
        getContentPane().add(JBT18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 110, -1));

        JBT19.setBackground(new java.awt.Color(153, 51, 0));
        JBT19.setForeground(new java.awt.Color(255, 255, 255));
        JBT19.setText("CANON");
        JBT19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBT19ActionPerformed(evt);
            }
        });
        getContentPane().add(JBT19, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 110, -1));

        JBT21.setBackground(new java.awt.Color(153, 51, 0));
        JBT21.setForeground(new java.awt.Color(255, 255, 255));
        JBT21.setText("ROCKET");
        JBT21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBT21ActionPerformed(evt);
            }
        });
        getContentPane().add(JBT21, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, 110, -1));

        TB1.setBackground(new java.awt.Color(153, 51, 0));
        TB1.setFont(new java.awt.Font("Liberation Mono", 1, 15)); // NOI18N
        TB1.setForeground(new java.awt.Color(255, 255, 255));
        TB1.setText("A-T-W");
        TB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TB1ActionPerformed(evt);
            }
        });
        getContentPane().add(TB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 120, -1));

        JLB11.setFont(new java.awt.Font("Liberation Mono", 1, 15)); // NOI18N
        JLB11.setText("OFF");
        getContentPane().add(JLB11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 300, 20));

        TB2.setBackground(new java.awt.Color(153, 51, 0));
        TB2.setFont(new java.awt.Font("Liberation Mono", 1, 15)); // NOI18N
        TB2.setForeground(new java.awt.Color(255, 255, 255));
        TB2.setText("S-A-R");
        TB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TB2ActionPerformed(evt);
            }
        });
        getContentPane().add(TB2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 120, -1));

        TB3.setBackground(new java.awt.Color(153, 51, 0));
        TB3.setFont(new java.awt.Font("Liberation Mono", 1, 15)); // NOI18N
        TB3.setForeground(new java.awt.Color(255, 255, 255));
        TB3.setText("TURBO");
        TB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TB3ActionPerformed(evt);
            }
        });
        getContentPane().add(TB3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 120, -1));

        TB4.setBackground(new java.awt.Color(153, 51, 0));
        TB4.setFont(new java.awt.Font("Liberation Mono", 1, 15)); // NOI18N
        TB4.setForeground(new java.awt.Color(255, 255, 255));
        TB4.setText("CABLE");
        TB4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TB4ActionPerformed(evt);
            }
        });
        getContentPane().add(TB4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 120, -1));

        JLB14.setFont(new java.awt.Font("Liberation Mono", 1, 15)); // NOI18N
        JLB14.setText("OFF");
        getContentPane().add(JLB14, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 160, 20));

        TB5.setBackground(new java.awt.Color(153, 51, 0));
        TB5.setFont(new java.awt.Font("Liberation Mono", 1, 15)); // NOI18N
        TB5.setForeground(new java.awt.Color(255, 255, 255));
        TB5.setText("F-L");
        TB5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TB5ActionPerformed(evt);
            }
        });
        getContentPane().add(TB5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 120, -1));

        JLB15.setFont(new java.awt.Font("Liberation Mono", 1, 15)); // NOI18N
        JLB15.setText("OFF");
        getContentPane().add(JLB15, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 250, 20));

        TB6.setBackground(new java.awt.Color(153, 51, 0));
        TB6.setFont(new java.awt.Font("Liberation Mono", 1, 15)); // NOI18N
        TB6.setForeground(new java.awt.Color(255, 255, 255));
        TB6.setText("EMERGENCY");
        TB6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TB6ActionPerformed(evt);
            }
        });
        getContentPane().add(TB6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 120, -1));

        JLB16.setFont(new java.awt.Font("Liberation Mono", 1, 15)); // NOI18N
        JLB16.setText("OFF");
        getContentPane().add(JLB16, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 240, 20));

        jTextField1.setBackground(new java.awt.Color(153, 51, 0));
        jTextField1.setText("MAPING WATING");
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 410, 350, 50));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("AMMOR");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, 70, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("SOLDER");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, -1, -1));

        jSlider6.setBackground(new java.awt.Color(0, 0, 0));
        jSlider6.setForeground(new java.awt.Color(153, 51, 0));
        jSlider6.setMaximum(100000);
        jSlider6.setMinimum(1000);
        jSlider6.setOrientation(javax.swing.JSlider.VERTICAL);
        jSlider6.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider6StateChanged(evt);
            }
        });
        getContentPane().add(jSlider6, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 60, -1, -1));

        jTextField2.setBackground(new java.awt.Color(153, 51, 0));
        jTextField2.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2.setText("1000");
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 20, 100, -1));

        jTextField5.setBackground(new java.awt.Color(153, 51, 0));
        jTextField5.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(255, 255, 255));
        jTextField5.setText("33");
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 100, -1));

        jTextField6.setBackground(new java.awt.Color(153, 51, 0));
        jTextField6.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(255, 255, 255));
        jTextField6.setText("100");
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 370, 80, -1));

        jLabel4.setFont(new java.awt.Font("Liberation Serif", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("fan speed");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 350, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("turbo speed");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, 100, -1));

        jLabel6.setText("engin power");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 0, 100, -1));

        JLB12.setBackground(new java.awt.Color(102, 0, 0));
        JLB12.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        JLB12.setText("OFF");
        getContentPane().add(JLB12, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 230, -1));

        JLB13.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        JLB13.setText("OFF");
        getContentPane().add(JLB13, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 230, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon("/home/macami-3/NetBeansProjects/slarmy/0MtVjZN.jpg")); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1100, 540));

        getAccessibleContext().setAccessibleName("helicopter");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField2ActionPerformed

    private void JBT4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBT4ActionPerformed
boolean B4 = JRB5.isSelected();
    if (B4==true){
    JLB5.setText(" ON");
    }
    else{
    JLB5.setText(" OFF");}
            // TODO add your handling code here:
    }//GEN-LAST:event_JBT4ActionPerformed

    private void JBT7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBT7ActionPerformed
boolean B7 = JRB9.isSelected();
    if (B7==true){
    JLB8.setText(" OPEN");
    }
    else{
    JLB8.setText(" CLOSE");}        // TODO add your handling code here:
    }//GEN-LAST:event_JBT7ActionPerformed

    private void JBT8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBT8ActionPerformed
boolean B8 = JRB8.isSelected();
    if (B8==true){
    JLB9.setText(" ON");
    }
    else{
    JLB9.setText(" OFF");}        // TODO add your handling code here:
    }//GEN-LAST:event_JBT8ActionPerformed

    private void JBT9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBT9ActionPerformed
boolean B9 = JRB10.isSelected();
    if (B9==true){
    JLB10.setText(" START");
    }
    else{
    JLB10.setText(" STOP");}        // TODO add your handling code here:
    }//GEN-LAST:event_JBT9ActionPerformed

    private void JBT10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBT10ActionPerformed
//textField1.setText("msseg send "); 
 
    }//GEN-LAST:event_JBT10ActionPerformed

    private void JBT11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBT11ActionPerformed
boolean B10 = JRB1.isSelected();
    if (B10==true){
    JLB1.setText(" AOUTO ENABLE");
    }
    else{
    JLB1.setText(" AOUTO DISABLE");}        // TODO add your handling code here:
    }//GEN-LAST:event_JBT11ActionPerformed

    private void JBT12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBT12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBT12ActionPerformed

    private void JBT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBT1ActionPerformed
boolean B1 = JRB2.isSelected();
    if (B1==true){
    JLB2.setText(" ON");
    }
    else{
    JLB2.setText(" OFF");}
            // TODO add your handling code here:
    }//GEN-LAST:event_JBT1ActionPerformed

    private void textField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField1ActionPerformed

    private void JBT2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBT2ActionPerformed
    boolean B2 = JRB3.isSelected();
    if (B2==true){
    JLB3.setText(" ON");
    }
    else{
    JLB3.setText(" OFF");}
        // TODO add your handling code here:
    }//GEN-LAST:event_JBT2ActionPerformed

    private void JBT3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBT3ActionPerformed
boolean B3 = JRB4.isSelected();
    if (B3==true){
    JLB4.setText(" ON");
    }
    else{
    JLB4.setText(" OFF");}
            // TODO add your handling code here:
    }//GEN-LAST:event_JBT3ActionPerformed

    private void JBT5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBT5ActionPerformed
boolean B5 = JRB6.isSelected();
    if (B5==true){
    JLB6.setText(" ON");
    }
    else{
    JLB6.setText(" OFF");}
            // TODO add your handling code here:
    }//GEN-LAST:event_JBT5ActionPerformed

    private void JBT6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBT6ActionPerformed
boolean B6 = JRB7.isSelected();
    if (B6==true){
    JLB7.setText(" ON");
    }
    else{
    JLB7.setText("OFF");}
            // TODO add your handling code here:
    }//GEN-LAST:event_JBT6ActionPerformed

    private void JBT13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBT13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBT13ActionPerformed

    private void JBT14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBT14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBT14ActionPerformed

    private void JBT16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBT16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBT16ActionPerformed

    private void JBT17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBT17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBT17ActionPerformed

    private void JBT18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBT18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBT18ActionPerformed

    private void JBT19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBT19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBT19ActionPerformed

    private void JBT21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBT21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBT21ActionPerformed

    private void TB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TB1ActionPerformed
if(TB1.isSelected()){
    JLB11.setText("Anti-Tank Warfare:ON");
}
else{
    JLB11.setText("Anti-Tank Warfare:OFF");
}
    }//GEN-LAST:event_TB1ActionPerformed

    private void TB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TB2ActionPerformed
if(TB2.isSelected()){
    JLB12.setText("Search and Rescue :active");
}
else{
    JLB12.setText("Search and Rescue :deactivate");
}        // TODO add your handling code here:
    }//GEN-LAST:event_TB2ActionPerformed

    private void TB3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TB3ActionPerformed
      if(TB3.isSelected()){
    JLB13.setText("TURBO:active");
}
else{
    JLB13.setText("TURBO:deactivate");
}  // TODO add your handling code here:
    }//GEN-LAST:event_TB3ActionPerformed

    private void TB4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TB4ActionPerformed
if(TB4.isSelected()){
    JLB14.setText("CABLE :ON");
}
else{
    JLB14.setText("CABLE:OFF");
}        // TODO add your handling code here:
    }//GEN-LAST:event_TB4ActionPerformed

    private void TB5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TB5ActionPerformed
if(TB5.isSelected()){
    JLB15.setText("FAST LANDING:active");
}
else{
    JLB15.setText("FAST LANDING:deactivate");
}        // TODO add your handling code here:
    }//GEN-LAST:event_TB5ActionPerformed

    private void TB6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TB6ActionPerformed
if(TB6.isSelected()){
    JLB16.setText(" respond quickly ON ");
}
else{
    JLB16.setText("OFF");
}        // TODO add your handling code here:
    }//GEN-LAST:event_TB6ActionPerformed

    private void jSlider5StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider5StateChanged
int a =jSlider5.getValue();
jTextField5.setText(String.valueOf(a));
// TODO add your handling code here:
    }//GEN-LAST:event_jSlider5StateChanged

    private void jSlider4StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider4StateChanged
int b= jSlider4.getValue();
jTextField6.setText(String.valueOf(b));// TODO add your handling code here:
    }//GEN-LAST:event_jSlider4StateChanged

    private void jSlider6StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider6StateChanged
int k=jSlider6.getValue();
jTextField2.setText(String.valueOf(k));// TODO add your handling code here:
    }//GEN-LAST:event_jSlider6StateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(helicopter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(helicopter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(helicopter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(helicopter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new helicopter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBT1;
    private javax.swing.JButton JBT10;
    private javax.swing.JButton JBT11;
    private javax.swing.JButton JBT12;
    private javax.swing.JButton JBT13;
    private javax.swing.JButton JBT14;
    private javax.swing.JButton JBT16;
    private javax.swing.JButton JBT17;
    private javax.swing.JButton JBT18;
    private javax.swing.JButton JBT19;
    private javax.swing.JButton JBT2;
    private javax.swing.JButton JBT21;
    private javax.swing.JButton JBT3;
    private javax.swing.JButton JBT4;
    private javax.swing.JButton JBT5;
    private javax.swing.JButton JBT6;
    private javax.swing.JButton JBT7;
    private javax.swing.JButton JBT8;
    private javax.swing.JButton JBT9;
    private javax.swing.JLabel JLB1;
    private javax.swing.JLabel JLB10;
    private javax.swing.JLabel JLB11;
    private javax.swing.JLabel JLB12;
    private javax.swing.JLabel JLB13;
    private javax.swing.JLabel JLB14;
    private javax.swing.JLabel JLB15;
    private javax.swing.JLabel JLB16;
    private javax.swing.JLabel JLB2;
    private javax.swing.JLabel JLB3;
    private javax.swing.JLabel JLB4;
    private javax.swing.JLabel JLB5;
    private javax.swing.JLabel JLB6;
    private javax.swing.JLabel JLB7;
    private javax.swing.JLabel JLB8;
    private javax.swing.JLabel JLB9;
    private javax.swing.JRadioButton JRB1;
    private javax.swing.JRadioButton JRB10;
    private javax.swing.JRadioButton JRB2;
    private javax.swing.JRadioButton JRB3;
    private javax.swing.JRadioButton JRB4;
    private javax.swing.JRadioButton JRB5;
    private javax.swing.JRadioButton JRB6;
    private javax.swing.JRadioButton JRB7;
    private javax.swing.JRadioButton JRB8;
    private javax.swing.JRadioButton JRB9;
    private javax.swing.JToggleButton TB1;
    private javax.swing.JToggleButton TB2;
    private javax.swing.JToggleButton TB3;
    private javax.swing.JToggleButton TB4;
    private javax.swing.JToggleButton TB5;
    private javax.swing.JToggleButton TB6;
    private java.awt.Checkbox checkbox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSlider jSlider4;
    private javax.swing.JSlider jSlider5;
    private javax.swing.JSlider jSlider6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private java.awt.Scrollbar scrollbar1;
    private java.awt.Scrollbar scrollbar2;
    private java.awt.TextField textField1;
    private java.awt.TextField textField2;
    // End of variables declaration//GEN-END:variables
}
