/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author macami-3
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public main() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jLabel3 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        JC1 = new javax.swing.JComboBox<>();
        B1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        T1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSlider1 = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        B2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TP1 = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        TP2 = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        TP3 = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextPane4 = new javax.swing.JTextPane();
        jButton2 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        CB1 = new java.awt.Checkbox();
        CB2 = new java.awt.Checkbox();
        textField1 = new java.awt.TextField();
        jButton3 = new javax.swing.JButton();
        JL5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        JB4 = new javax.swing.JButton();
        textArea3 = new java.awt.TextArea();
        jButton4 = new javax.swing.JButton();
        textArea5 = new java.awt.TextArea();
        TA6 = new java.awt.TextArea();
        JL4 = new javax.swing.JLabel();
        JRB2 = new javax.swing.JRadioButton();
        JL6 = new javax.swing.JLabel();
        JB5 = new javax.swing.JButton();
        JL7 = new javax.swing.JLabel();
        JL8 = new javax.swing.JLabel();
        JB6 = new javax.swing.JButton();
        JRB1 = new javax.swing.JRadioButton();
        JLB9 = new javax.swing.JLabel();
        JL3 = new javax.swing.JLabel();
        JRB3 = new javax.swing.JRadioButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        jToolBar1.setRollover(true);

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("mainroom");
        setBackground(new java.awt.Color(51, 51, 51));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JC1.setBackground(new java.awt.Color(51, 51, 51));
        JC1.setForeground(new java.awt.Color(255, 255, 255));
        JC1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select defence", "tank", "submarine", "helicopter" }));
        JC1.setToolTipText("");
        JC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JC1ActionPerformed(evt);
            }
        });
        getContentPane().add(JC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 370, 170, -1));

        B1.setBackground(new java.awt.Color(51, 51, 51));
        B1.setForeground(new java.awt.Color(255, 255, 255));
        B1.setText("collec imformationt");
        B1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B1ActionPerformed(evt);
            }
        });
        getContentPane().add(B1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 200, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText(" Fuel amount");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, -1, -1));

        T1.setForeground(new java.awt.Color(255, 255, 255));
        T1.setText("Ammo amonut");
        getContentPane().add(T1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Position");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        jSlider1.setBackground(new java.awt.Color(255, 0, 0));
        jSlider1.setForeground(new java.awt.Color(255, 255, 255));
        jSlider1.setMinorTickSpacing(20);
        jSlider1.setPaintTicks(true);
        jSlider1.setValue(0);
        jSlider1.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        jSlider1.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);
        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider1StateChanged(evt);
            }
        });
        getContentPane().add(jSlider1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, -1, -1));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Solder count");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, -1, -1));

        B2.setBackground(new java.awt.Color(153, 0, 0));
        B2.setText("call මහ්සො නා");
        B2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B2ActionPerformed(evt);
            }
        });
        getContentPane().add(B2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, 130, -1));

        jTextField1.setBackground(new java.awt.Color(51, 51, 51));
        jTextField1.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, 130, -1));

        jButton1.setBackground(new java.awt.Color(255, 51, 51));
        jButton1.setText("call a swat team");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, -1, -1));

        jTextField2.setBackground(new java.awt.Color(51, 51, 51));
        jTextField2.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 40, 136, -1));

        TP1.setBackground(new java.awt.Color(51, 51, 51));
        TP1.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(TP1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 80, -1));

        TP2.setBackground(new java.awt.Color(51, 51, 51));
        TP2.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(TP2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 80, -1));

        TP3.setBackground(new java.awt.Color(51, 51, 51));
        TP3.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane3.setViewportView(TP3);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 80, -1));

        jTextPane4.setBackground(new java.awt.Color(51, 51, 51));
        jTextPane4.setForeground(new java.awt.Color(255, 255, 255));
        jTextPane4.setText("00");
        jScrollPane4.setViewportView(jTextPane4);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 80, -1));

        jButton2.setBackground(new java.awt.Color(255, 102, 102));
        jButton2.setText("call FBI team");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, 124, -1));

        jTextField3.setBackground(new java.awt.Color(51, 51, 51));
        jTextField3.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 40, 124, -1));

        CB1.setBackground(new java.awt.Color(51, 51, 51));
        CB1.setForeground(new java.awt.Color(255, 255, 255));
        CB1.setLabel("Area Clear");
        getContentPane().add(CB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 10, 170, -1));

        CB2.setBackground(new java.awt.Color(51, 51, 51));
        CB2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        CB2.setForeground(new java.awt.Color(255, 255, 255));
        CB2.setLabel("ultra power");
        getContentPane().add(CB2, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 40, 170, -1));

        textField1.setBackground(new java.awt.Color(51, 51, 51));
        textField1.setEditable(false);
        textField1.setFont(new java.awt.Font("Noto Serif CJK KR", 1, 36)); // NOI18N
        textField1.setForeground(new java.awt.Color(255, 255, 255));
        textField1.setText("GOST ARMY TEAM");
        textField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField1ActionPerformed(evt);
            }
        });
        getContentPane().add(textField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 50));

        jButton3.setBackground(new java.awt.Color(51, 51, 51));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("calculate");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 190, -1));

        JL5.setBackground(new java.awt.Color(255, 102, 102));
        JL5.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(JL5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 110, 20));

        jTextField4.setBackground(new java.awt.Color(51, 51, 51));
        jTextField4.setForeground(new java.awt.Color(255, 255, 255));
        jTextField4.setText("FIRE RATE");
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 190, 30));

        JB4.setBackground(new java.awt.Color(51, 51, 51));
        JB4.setForeground(new java.awt.Color(255, 255, 255));
        JB4.setText("OK");
        JB4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB4ActionPerformed(evt);
            }
        });
        getContentPane().add(JB4, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 70, 170, -1));

        textArea3.setBackground(new java.awt.Color(51, 51, 51));
        textArea3.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(textArea3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 220, -1));

        jButton4.setBackground(new java.awt.Color(51, 51, 51));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("send masseg");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 420, 170, -1));

        textArea5.setBackground(new java.awt.Color(51, 51, 51));
        textArea5.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(textArea5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 420, 220, -1));

        TA6.setBackground(new java.awt.Color(51, 51, 51));
        TA6.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(TA6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 420, 220, -1));

        JL4.setFont(new java.awt.Font("Noto Sans CJK SC", 1, 18)); // NOI18N
        JL4.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(JL4, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 450, 360, 80));

        JRB2.setForeground(new java.awt.Color(255, 255, 255));
        JRB2.setText("මහසො නා  activet");
        getContentPane().add(JRB2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, -1, -1));

        JL6.setFont(new java.awt.Font("Bitstream Charter", 1, 18)); // NOI18N
        JL6.setForeground(new java.awt.Color(255, 255, 255));
        JL6.setText("NO ACTIVE");
        getContentPane().add(JL6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, 260, 30));

        JB5.setBackground(new java.awt.Color(51, 51, 51));
        JB5.setForeground(new java.awt.Color(255, 255, 255));
        JB5.setText("activate");
        JB5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB5ActionPerformed(evt);
            }
        });
        getContentPane().add(JB5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 140, -1));

        JL7.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        JL7.setForeground(new java.awt.Color(255, 255, 255));
        JL7.setText("NO ACTIVE");
        getContentPane().add(JL7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, 280, 30));

        JL8.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        JL8.setForeground(new java.awt.Color(255, 255, 255));
        JL8.setText("NO ACTIVE");
        getContentPane().add(JL8, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 250, 280, 30));

        JB6.setBackground(new java.awt.Color(51, 51, 51));
        JB6.setForeground(new java.awt.Color(255, 255, 255));
        JB6.setText("activate");
        JB6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB6ActionPerformed(evt);
            }
        });
        getContentPane().add(JB6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 140, -1));

        JRB1.setForeground(new java.awt.Color(255, 255, 255));
        JRB1.setText("SPECIAL FORCE");
        JRB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRB1ActionPerformed(evt);
            }
        });
        getContentPane().add(JRB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, -1, -1));

        JLB9.setFont(new java.awt.Font("TlwgTypewriter", 1, 18)); // NOI18N
        JLB9.setForeground(new java.awt.Color(255, 255, 255));
        JLB9.setText("WATING INFOR");
        getContentPane().add(JLB9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 300, -1));

        JL3.setFont(new java.awt.Font("Likhan", 1, 24)); // NOI18N
        JL3.setForeground(new java.awt.Color(255, 255, 255));
        JL3.setText("AREA OK");
        getContentPane().add(JL3, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 110, 200, 50));

        JRB3.setForeground(new java.awt.Color(255, 255, 255));
        JRB3.setText("DELTA FORCE");
        JRB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRB3ActionPerformed(evt);
            }
        });
        getContentPane().add(JRB3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, -1, -1));

        jButton5.setBackground(new java.awt.Color(51, 51, 51));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("activate");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 140, -1));

        jButton6.setBackground(new java.awt.Color(51, 51, 51));
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("tank");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 380, 100, -1));

        jButton8.setBackground(new java.awt.Color(51, 51, 51));
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("helicopter");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, -1, -1));

        jButton9.setBackground(new java.awt.Color(51, 51, 51));
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("subnarine");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 380, 100, -1));

        jButton10.setBackground(new java.awt.Color(51, 51, 51));
        jButton10.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("BACK");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 370, 110, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon("/home/macami-3/NetBeansProjects/slarmy/rJmNY1.jpg")); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, -270, 1800, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B1ActionPerformed
JLB9.setText("IMFORMATION COLLECTING");
    }//GEN-LAST:event_B1ActionPerformed

    private void B2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B2ActionPerformed
jTextField1.setText("මහසො නා in coming");  
    }//GEN-LAST:event_B2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
jTextField2.setText("calling swat team");        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
jTextField3.setText("FBI incoming");        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void JC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JC1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JC1ActionPerformed

    private void textField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
String no1=TP1.getText();
String no2=TP2.getText();
String no3=TP3.getText();
int x1 =Integer.parseInt(no1);
int x2 =Integer.parseInt(no2);
int x3 =Integer.parseInt(no3);
int sum =(x1+x2)/x3;
String F=Integer.toString(sum);

JL5.setText(F);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void JB4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB4ActionPerformed
boolean x=CB1.getState();
boolean y=CB2.getState();
if(x==true&&y==true){
    JL3.setText("super power");}      
else{JL3.setText("damege high");}
    }//GEN-LAST:event_JB4ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String defence = JC1.getSelectedItem().toString();
     JL4.setText(defence+"  ACTIVATE GOST ARMY");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void JB5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB5ActionPerformed
    boolean u = JRB2.isSelected();
    if (u==true){
    JL6.setText("මහසො නා INCOMING ACTIVATE");
    }
    else{
    JL6.setText("ACTIVATE FAIL");}
    
        
    
        
           
    }//GEN-LAST:event_JB5ActionPerformed

    private void JB6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB6ActionPerformed
       boolean L = JRB1.isSelected();
       if (L==true){
    JL7.setText("SPECIAL FORCE ACTIVATE");
       }
       else{JL7.setText("ACTIVATE FAIL");
       }
    }//GEN-LAST:event_JB6ActionPerformed

    private void JRB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRB1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JRB1ActionPerformed

    private void JRB3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRB3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JRB3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
boolean t = JRB3.isSelected();
       if (t==true){
    JL8.setText("DELTA FORCE ACTIVATE");
       }
       else{JL8.setText("ACTIVATE FAIL");
       }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
     tank H1 =new tank();
     H1.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider1StateChanged
int slide=jSlider1.getValue();
jTextPane4.setText(String.valueOf(slide));// TODO add your handling code here:
    }//GEN-LAST:event_jSlider1StateChanged

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
helicopter H =new helicopter();
    H.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
      submarine H2 =new submarine();
     H2.setVisible(true);  // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
home h= new home();
h.setVisible(true);
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed
           

   
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B1;
    private javax.swing.JButton B2;
    private java.awt.Checkbox CB1;
    private java.awt.Checkbox CB2;
    private javax.swing.JButton JB4;
    private javax.swing.JButton JB5;
    private javax.swing.JButton JB6;
    private javax.swing.JComboBox<String> JC1;
    private javax.swing.JLabel JL3;
    private javax.swing.JLabel JL4;
    private javax.swing.JLabel JL5;
    private javax.swing.JLabel JL6;
    private javax.swing.JLabel JL7;
    private javax.swing.JLabel JL8;
    private javax.swing.JLabel JLB9;
    private javax.swing.JRadioButton JRB1;
    private javax.swing.JRadioButton JRB2;
    private javax.swing.JRadioButton JRB3;
    private javax.swing.JLabel T1;
    private java.awt.TextArea TA6;
    private javax.swing.JTextPane TP1;
    private javax.swing.JTextPane TP2;
    private javax.swing.JTextPane TP3;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextPane jTextPane4;
    private javax.swing.JToolBar jToolBar1;
    private java.awt.TextArea textArea3;
    private java.awt.TextArea textArea5;
    private java.awt.TextField textField1;
    // End of variables declaration//GEN-END:variables
}
