/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author macami-3
 */
public class submarine extends javax.swing.JFrame {

    /**
     * Creates new form submarine
     */
    public submarine() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        JB2 = new javax.swing.JButton();
        TB1 = new javax.swing.JToggleButton();
        jSlider3 = new javax.swing.JSlider();
        TB2 = new javax.swing.JToggleButton();
        jSlider4 = new javax.swing.JSlider();
        TB3 = new javax.swing.JToggleButton();
        jSlider5 = new javax.swing.JSlider();
        TB4 = new javax.swing.JToggleButton();
        jSlider6 = new javax.swing.JSlider();
        TB5 = new javax.swing.JToggleButton();
        jSlider7 = new javax.swing.JSlider();
        TB6 = new javax.swing.JToggleButton();
        jSlider8 = new javax.swing.JSlider();
        TB7 = new javax.swing.JToggleButton();
        jSlider9 = new javax.swing.JSlider();
        TF1 = new javax.swing.JTextField();
        TF2 = new javax.swing.JTextField();
        TF3 = new javax.swing.JTextField();
        TF4 = new javax.swing.JTextField();
        TF5 = new javax.swing.JTextField();
        TF6 = new javax.swing.JTextField();
        TF7 = new javax.swing.JTextField();
        textField1 = new java.awt.TextField();
        JB3 = new javax.swing.JButton();
        JB4 = new javax.swing.JButton();
        JB5 = new javax.swing.JButton();
        JB6 = new javax.swing.JButton();
        JB7 = new javax.swing.JButton();
        JB8 = new javax.swing.JButton();
        JB9 = new javax.swing.JButton();
        JB10 = new javax.swing.JButton();
        JB11 = new javax.swing.JButton();
        textField2 = new java.awt.TextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        scrollbar1 = new java.awt.Scrollbar();
        scrollbar2 = new java.awt.Scrollbar();
        scrollbar3 = new java.awt.Scrollbar();
        scrollbar4 = new java.awt.Scrollbar();
        scrollbar5 = new java.awt.Scrollbar();
        scrollbar6 = new java.awt.Scrollbar();
        checkbox1 = new java.awt.Checkbox();
        checkbox2 = new java.awt.Checkbox();
        jSlider1 = new javax.swing.JSlider();
        jSlider2 = new javax.swing.JSlider();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        textField3 = new java.awt.TextField();
        textField4 = new java.awt.TextField();
        scrollbar7 = new java.awt.Scrollbar();
        scrollbar8 = new java.awt.Scrollbar();
        scrollbar9 = new java.awt.Scrollbar();
        scrollbar10 = new java.awt.Scrollbar();
        scrollbar11 = new java.awt.Scrollbar();
        scrollbar12 = new java.awt.Scrollbar();
        scrollbar13 = new java.awt.Scrollbar();
        scrollbar14 = new java.awt.Scrollbar();
        scrollbar15 = new java.awt.Scrollbar();
        scrollbar16 = new java.awt.Scrollbar();
        scrollbar17 = new java.awt.Scrollbar();
        scrollbar18 = new java.awt.Scrollbar();
        scrollbar20 = new java.awt.Scrollbar();
        scrollbar21 = new java.awt.Scrollbar();
        scrollbar22 = new java.awt.Scrollbar();
        scrollbar23 = new java.awt.Scrollbar();
        scrollbar24 = new java.awt.Scrollbar();
        TB8 = new javax.swing.JToggleButton();
        jSlider10 = new javax.swing.JSlider();
        TF8 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        JL6 = new javax.swing.JLabel();
        JL7 = new javax.swing.JLabel();
        JL8 = new javax.swing.JLabel();
        JL9 = new javax.swing.JLabel();
        JL10 = new javax.swing.JLabel();
        JL11 = new javax.swing.JLabel();
        JL12 = new javax.swing.JLabel();
        JL13 = new javax.swing.JLabel();
        jSpinner2 = new javax.swing.JSpinner();
        JL14 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jLabel3.setIcon(new javax.swing.ImageIcon("/home/macami-3/NetBeansProjects/slarmy/bDtKlV.jpg")); // NOI18N
        jLabel3.setText("jLabel3");

        jLabel5.setIcon(new javax.swing.ImageIcon("/home/macami-3/NetBeansProjects/slarmy/bDtKlV.jpg")); // NOI18N
        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("submarine");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JB2.setBackground(new java.awt.Color(0, 51, 51));
        JB2.setForeground(new java.awt.Color(255, 255, 255));
        JB2.setText("NEYUCLER");
        JB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB2ActionPerformed(evt);
            }
        });
        getContentPane().add(JB2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 90, -1));

        TB1.setBackground(new java.awt.Color(0, 51, 51));
        TB1.setForeground(new java.awt.Color(255, 255, 255));
        TB1.setText("A");
        TB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TB1ActionPerformed(evt);
            }
        });
        getContentPane().add(TB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 320, 30, 90));

        jSlider3.setBackground(new java.awt.Color(0, 51, 51));
        jSlider3.setForeground(new java.awt.Color(255, 255, 255));
        jSlider3.setOrientation(javax.swing.JSlider.VERTICAL);
        jSlider3.setValue(0);
        jSlider3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider3StateChanged(evt);
            }
        });
        getContentPane().add(jSlider3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, -1, -1));

        TB2.setBackground(new java.awt.Color(0, 51, 51));
        TB2.setForeground(new java.awt.Color(255, 255, 255));
        TB2.setText("B");
        TB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TB2ActionPerformed(evt);
            }
        });
        getContentPane().add(TB2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 320, 30, 90));

        jSlider4.setBackground(new java.awt.Color(0, 51, 51));
        jSlider4.setForeground(new java.awt.Color(255, 255, 255));
        jSlider4.setOrientation(javax.swing.JSlider.VERTICAL);
        jSlider4.setValue(0);
        jSlider4.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider4StateChanged(evt);
            }
        });
        getContentPane().add(jSlider4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 120, -1, -1));

        TB3.setBackground(new java.awt.Color(0, 51, 51));
        TB3.setForeground(new java.awt.Color(255, 255, 255));
        TB3.setText("C");
        TB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TB3ActionPerformed(evt);
            }
        });
        getContentPane().add(TB3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 320, 30, 90));

        jSlider5.setBackground(new java.awt.Color(0, 51, 51));
        jSlider5.setForeground(new java.awt.Color(255, 255, 255));
        jSlider5.setOrientation(javax.swing.JSlider.VERTICAL);
        jSlider5.setValue(0);
        jSlider5.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider5StateChanged(evt);
            }
        });
        getContentPane().add(jSlider5, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 120, -1, -1));

        TB4.setBackground(new java.awt.Color(0, 51, 51));
        TB4.setForeground(new java.awt.Color(255, 255, 255));
        TB4.setText("D");
        TB4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TB4ActionPerformed(evt);
            }
        });
        getContentPane().add(TB4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 320, 30, 90));

        jSlider6.setBackground(new java.awt.Color(0, 51, 51));
        jSlider6.setForeground(new java.awt.Color(255, 255, 255));
        jSlider6.setOrientation(javax.swing.JSlider.VERTICAL);
        jSlider6.setValue(0);
        jSlider6.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider6StateChanged(evt);
            }
        });
        getContentPane().add(jSlider6, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 120, -1, -1));

        TB5.setBackground(new java.awt.Color(0, 51, 51));
        TB5.setForeground(new java.awt.Color(255, 255, 255));
        TB5.setText("E");
        TB5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TB5ActionPerformed(evt);
            }
        });
        getContentPane().add(TB5, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 320, 30, 90));

        jSlider7.setBackground(new java.awt.Color(0, 51, 51));
        jSlider7.setForeground(new java.awt.Color(255, 255, 255));
        jSlider7.setOrientation(javax.swing.JSlider.VERTICAL);
        jSlider7.setValue(0);
        jSlider7.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider7StateChanged(evt);
            }
        });
        getContentPane().add(jSlider7, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 120, -1, -1));

        TB6.setBackground(new java.awt.Color(0, 51, 51));
        TB6.setForeground(new java.awt.Color(255, 255, 255));
        TB6.setText("F");
        TB6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TB6ActionPerformed(evt);
            }
        });
        getContentPane().add(TB6, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 320, 30, 90));

        jSlider8.setBackground(new java.awt.Color(0, 51, 51));
        jSlider8.setForeground(new java.awt.Color(255, 255, 255));
        jSlider8.setOrientation(javax.swing.JSlider.VERTICAL);
        jSlider8.setValue(0);
        jSlider8.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider8StateChanged(evt);
            }
        });
        getContentPane().add(jSlider8, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 120, -1, -1));

        TB7.setBackground(new java.awt.Color(0, 51, 51));
        TB7.setForeground(new java.awt.Color(255, 255, 255));
        TB7.setText("G");
        TB7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TB7ActionPerformed(evt);
            }
        });
        getContentPane().add(TB7, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 320, 30, 90));

        jSlider9.setBackground(new java.awt.Color(0, 51, 51));
        jSlider9.setForeground(new java.awt.Color(255, 255, 255));
        jSlider9.setOrientation(javax.swing.JSlider.VERTICAL);
        jSlider9.setValue(0);
        jSlider9.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider9StateChanged(evt);
            }
        });
        getContentPane().add(jSlider9, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 120, -1, -1));

        TF1.setBackground(new java.awt.Color(0, 51, 51));
        TF1.setForeground(new java.awt.Color(255, 255, 255));
        TF1.setText("00");
        getContentPane().add(TF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, 30, -1));

        TF2.setBackground(new java.awt.Color(0, 51, 51));
        TF2.setForeground(new java.awt.Color(255, 255, 255));
        TF2.setText("00");
        TF2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF2ActionPerformed(evt);
            }
        });
        getContentPane().add(TF2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 100, 30, -1));

        TF3.setBackground(new java.awt.Color(0, 51, 51));
        TF3.setForeground(new java.awt.Color(255, 255, 255));
        TF3.setText("00");
        getContentPane().add(TF3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 100, 30, -1));

        TF4.setBackground(new java.awt.Color(0, 51, 51));
        TF4.setForeground(new java.awt.Color(255, 255, 255));
        TF4.setText("00");
        getContentPane().add(TF4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 100, 30, -1));

        TF5.setBackground(new java.awt.Color(0, 51, 51));
        TF5.setForeground(new java.awt.Color(255, 255, 255));
        TF5.setText("00");
        getContentPane().add(TF5, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 100, 30, -1));

        TF6.setBackground(new java.awt.Color(0, 51, 51));
        TF6.setForeground(new java.awt.Color(255, 255, 255));
        TF6.setText("00");
        getContentPane().add(TF6, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 100, 30, -1));

        TF7.setBackground(new java.awt.Color(0, 51, 51));
        TF7.setForeground(new java.awt.Color(255, 255, 255));
        TF7.setText("00");
        TF7.setToolTipText("");
        getContentPane().add(TF7, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 100, 30, -1));

        textField1.setBackground(new java.awt.Color(0, 51, 51));
        textField1.setEditable(false);
        textField1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        textField1.setForeground(new java.awt.Color(255, 255, 255));
        textField1.setText("USA STEALTH");
        getContentPane().add(textField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 70));

        JB3.setBackground(new java.awt.Color(0, 51, 51));
        JB3.setForeground(new java.awt.Color(255, 255, 255));
        JB3.setText("SHOOT");
        JB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB3ActionPerformed(evt);
            }
        });
        getContentPane().add(JB3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        JB4.setBackground(new java.awt.Color(0, 51, 51));
        JB4.setForeground(new java.awt.Color(255, 255, 255));
        JB4.setText("BOMBS");
        JB4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB4ActionPerformed(evt);
            }
        });
        getContentPane().add(JB4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        JB5.setBackground(new java.awt.Color(0, 51, 51));
        JB5.setForeground(new java.awt.Color(255, 255, 255));
        JB5.setText("CANON");
        JB5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB5ActionPerformed(evt);
            }
        });
        getContentPane().add(JB5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        JB6.setBackground(new java.awt.Color(0, 51, 51));
        JB6.setForeground(new java.awt.Color(255, 255, 255));
        JB6.setText("SEND");
        JB6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB6ActionPerformed(evt);
            }
        });
        getContentPane().add(JB6, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 430, -1, -1));

        JB7.setBackground(new java.awt.Color(0, 51, 51));
        JB7.setForeground(new java.awt.Color(255, 255, 255));
        JB7.setText("TOPIDO");
        JB7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB7ActionPerformed(evt);
            }
        });
        getContentPane().add(JB7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, -1, -1));

        JB8.setBackground(new java.awt.Color(0, 51, 51));
        JB8.setForeground(new java.awt.Color(255, 255, 255));
        JB8.setText("SONAR");
        JB8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB8ActionPerformed(evt);
            }
        });
        getContentPane().add(JB8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, -1, -1));

        JB9.setBackground(new java.awt.Color(0, 51, 51));
        JB9.setForeground(new java.awt.Color(255, 255, 255));
        JB9.setText("R-P-GS");
        JB9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB9ActionPerformed(evt);
            }
        });
        getContentPane().add(JB9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, -1, -1));

        JB10.setBackground(new java.awt.Color(0, 51, 51));
        JB10.setForeground(new java.awt.Color(255, 255, 255));
        JB10.setText("ROCKET");
        JB10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB10ActionPerformed(evt);
            }
        });
        getContentPane().add(JB10, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 100, -1));

        JB11.setBackground(new java.awt.Color(0, 51, 51));
        JB11.setForeground(new java.awt.Color(255, 255, 255));
        JB11.setText("MISSILE");
        JB11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB11ActionPerformed(evt);
            }
        });
        getContentPane().add(JB11, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 90, -1));

        textField2.setBackground(new java.awt.Color(0, 51, 51));
        textField2.setForeground(new java.awt.Color(255, 255, 255));
        textField2.setText("TYPE MSSEG");
        getContentPane().add(textField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 430, 320, 30));

        jLabel1.setText("SOLDLER COUNT");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, -1, -1));

        jLabel2.setText("AMMOR COUNT");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, -1, -1));
        getContentPane().add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, -1, -1));

        scrollbar1.setBackground(new java.awt.Color(51, 255, 51));
        getContentPane().add(scrollbar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, -1, 80));

        scrollbar2.setBackground(new java.awt.Color(255, 51, 51));
        getContentPane().add(scrollbar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, -1, 80));

        scrollbar3.setBackground(new java.awt.Color(255, 0, 51));
        getContentPane().add(scrollbar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, -1, 80));

        scrollbar4.setBackground(new java.awt.Color(255, 255, 102));
        getContentPane().add(scrollbar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, -1, 80));

        scrollbar5.setBackground(new java.awt.Color(255, 255, 102));
        getContentPane().add(scrollbar5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, -1, 80));

        scrollbar6.setBackground(new java.awt.Color(51, 255, 51));
        getContentPane().add(scrollbar6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, -1, 80));

        checkbox1.setBackground(new java.awt.Color(0, 51, 51));
        checkbox1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        checkbox1.setForeground(new java.awt.Color(255, 255, 255));
        checkbox1.setLabel("AREA CLEAR");
        getContentPane().add(checkbox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        checkbox2.setBackground(new java.awt.Color(0, 51, 51));
        checkbox2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        checkbox2.setForeground(new java.awt.Color(255, 255, 255));
        checkbox2.setLabel("RADY DEFENS");
        getContentPane().add(checkbox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, -1, -1));

        jSlider1.setBackground(new java.awt.Color(255, 255, 255));
        jSlider1.setForeground(new java.awt.Color(0, 51, 51));
        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider1StateChanged(evt);
            }
        });
        getContentPane().add(jSlider1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        jSlider2.setBackground(new java.awt.Color(255, 255, 255));
        jSlider2.setForeground(new java.awt.Color(0, 51, 51));
        jSlider2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider2StateChanged(evt);
            }
        });
        getContentPane().add(jSlider2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        jTextArea1.setBackground(new java.awt.Color(0, 51, 51));
        jTextArea1.setColumns(20);
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, -1));

        textField3.setBackground(new java.awt.Color(0, 51, 51));
        textField3.setForeground(new java.awt.Color(255, 255, 255));
        textField3.setText("VALUE");
        getContentPane().add(textField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 70, -1));

        textField4.setBackground(new java.awt.Color(0, 51, 51));
        textField4.setForeground(new java.awt.Color(255, 255, 255));
        textField4.setText("VALUE");
        getContentPane().add(textField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 70, -1));

        scrollbar7.setBackground(new java.awt.Color(0, 51, 51));
        getContentPane().add(scrollbar7, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 0, -1, 90));

        scrollbar8.setBackground(new java.awt.Color(102, 102, 102));
        getContentPane().add(scrollbar8, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, -1, 90));

        scrollbar9.setBackground(new java.awt.Color(0, 51, 51));
        getContentPane().add(scrollbar9, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, -1, 90));

        scrollbar10.setBackground(new java.awt.Color(0, 102, 102));
        getContentPane().add(scrollbar10, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 0, -1, 90));

        scrollbar11.setBackground(new java.awt.Color(0, 51, 51));
        getContentPane().add(scrollbar11, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, -1, 90));

        scrollbar12.setBackground(new java.awt.Color(0, 255, 204));
        getContentPane().add(scrollbar12, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, -1, 90));

        scrollbar13.setBackground(new java.awt.Color(0, 51, 51));
        getContentPane().add(scrollbar13, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 0, -1, 90));

        scrollbar14.setBackground(new java.awt.Color(0, 51, 255));
        getContentPane().add(scrollbar14, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 0, -1, 90));

        scrollbar15.setBackground(new java.awt.Color(0, 51, 51));
        getContentPane().add(scrollbar15, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, -1, 90));

        scrollbar16.setBackground(new java.awt.Color(255, 255, 51));
        getContentPane().add(scrollbar16, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 0, -1, 90));

        scrollbar17.setBackground(new java.awt.Color(0, 51, 51));
        getContentPane().add(scrollbar17, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 0, -1, 90));

        scrollbar18.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(scrollbar18, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 0, -1, 90));

        scrollbar20.setBackground(new java.awt.Color(0, 51, 51));
        getContentPane().add(scrollbar20, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 0, -1, 90));

        scrollbar21.setBackground(new java.awt.Color(0, 51, 51));
        getContentPane().add(scrollbar21, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 0, -1, 90));

        scrollbar22.setBackground(new java.awt.Color(0, 51, 51));
        getContentPane().add(scrollbar22, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 0, -1, 90));

        scrollbar23.setBackground(new java.awt.Color(0, 51, 51));
        getContentPane().add(scrollbar23, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 0, -1, 90));

        scrollbar24.setBackground(new java.awt.Color(0, 51, 51));
        getContentPane().add(scrollbar24, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 0, -1, 90));

        TB8.setBackground(new java.awt.Color(0, 51, 51));
        TB8.setForeground(new java.awt.Color(255, 255, 255));
        TB8.setText("H");
        TB8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TB8ActionPerformed(evt);
            }
        });
        getContentPane().add(TB8, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 320, 30, 90));

        jSlider10.setBackground(new java.awt.Color(0, 51, 51));
        jSlider10.setForeground(new java.awt.Color(255, 255, 255));
        jSlider10.setOrientation(javax.swing.JSlider.VERTICAL);
        jSlider10.setValue(0);
        jSlider10.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider10StateChanged(evt);
            }
        });
        getContentPane().add(jSlider10, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 120, -1, -1));

        TF8.setBackground(new java.awt.Color(0, 51, 51));
        TF8.setForeground(new java.awt.Color(255, 255, 255));
        TF8.setText("00");
        getContentPane().add(TF8, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 100, 30, -1));

        jButton1.setBackground(new java.awt.Color(0, 51, 51));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("ACTIVE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 140, -1));

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("DEACTIVATE DEFENS");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, 350, 50));

        JL6.setFont(new java.awt.Font("Liberation Mono", 1, 24)); // NOI18N
        JL6.setForeground(new java.awt.Color(255, 0, 0));
        JL6.setText("ENGIN POWER CONTROLL UNIT SDI UNIT ");
        getContentPane().add(JL6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 490, 80));

        JL7.setFont(new java.awt.Font("Liberation Mono", 1, 15)); // NOI18N
        JL7.setForeground(new java.awt.Color(255, 255, 255));
        JL7.setText("FAN SPEED");
        getContentPane().add(JL7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 280, -1, -1));

        JL8.setFont(new java.awt.Font("Liberation Mono", 1, 15)); // NOI18N
        JL8.setForeground(new java.awt.Color(255, 255, 255));
        JL8.setText("TOURBO");
        getContentPane().add(JL8, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, 60, -1));

        JL9.setFont(new java.awt.Font("Liberation Mono", 1, 15)); // NOI18N
        JL9.setForeground(new java.awt.Color(255, 255, 255));
        JL9.setText("POWER EN");
        getContentPane().add(JL9, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 280, 110, 20));

        JL10.setFont(new java.awt.Font("Liberation Mono", 1, 15)); // NOI18N
        JL10.setForeground(new java.awt.Color(255, 255, 255));
        JL10.setText("LIGHTS NITS");
        getContentPane().add(JL10, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 250, 100, -1));

        JL11.setFont(new java.awt.Font("Liberation Mono", 1, 15)); // NOI18N
        JL11.setForeground(new java.awt.Color(255, 255, 255));
        JL11.setText("ENGINE OIL");
        getContentPane().add(JL11, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 280, 100, -1));

        JL12.setFont(new java.awt.Font("Liberation Mono", 1, 15)); // NOI18N
        JL12.setForeground(new java.awt.Color(255, 255, 255));
        JL12.setText("AMMOR SPEED");
        getContentPane().add(JL12, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 250, 100, -1));

        JL13.setFont(new java.awt.Font("Liberation Mono", 1, 15)); // NOI18N
        JL13.setForeground(new java.awt.Color(255, 255, 255));
        JL13.setText("CANON SPEED");
        getContentPane().add(JL13, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 280, 100, -1));
        getContentPane().add(jSpinner2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, -1, -1));

        JL14.setFont(new java.awt.Font("Liberation Mono", 1, 15)); // NOI18N
        JL14.setForeground(new java.awt.Color(255, 255, 255));
        JL14.setText("JET SPPED");
        getContentPane().add(JL14, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 250, 100, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon("/home/macami-3/NetBeansProjects/slarmy/bDtKlV.jpg")); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-460, -60, 1460, 780));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JB2ActionPerformed

    private void JB3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JB3ActionPerformed

    private void JB4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JB4ActionPerformed

    private void JB5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JB5ActionPerformed

    private void JB6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB6ActionPerformed
textField2.setText("MESSEG SENDING ");        // TODO add your handling code here:
    }//GEN-LAST:event_JB6ActionPerformed

    private void JB7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JB7ActionPerformed

    private void JB8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JB8ActionPerformed

    private void JB9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JB9ActionPerformed

    private void JB10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JB10ActionPerformed

    private void JB11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JB11ActionPerformed

    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider1StateChanged
int a =jSlider1.getValue();
textField4.setText(String.valueOf(a));         // TODO add your handling code here:
    }//GEN-LAST:event_jSlider1StateChanged

    private void jSlider2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider2StateChanged
      int a =jSlider2.getValue();
textField3.setText(String.valueOf(a)); // TODO add your handling code here:
    }//GEN-LAST:event_jSlider2StateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
boolean x=checkbox2.getState(); 
if(x==true){
scrollbar1.setVisible(true);
scrollbar2.setVisible(true);
scrollbar3.setVisible(true);
scrollbar4.setVisible(true);
scrollbar5.setVisible(true);
scrollbar6.setVisible(true);
scrollbar7.setVisible(true);
scrollbar8.setVisible(true);
scrollbar9.setVisible(true);
scrollbar10.setVisible(true);
scrollbar11.setVisible(true);
scrollbar12.setVisible(true);
scrollbar13.setVisible(true);
scrollbar14.setVisible(true);
scrollbar15.setVisible(true);
scrollbar16.setVisible(true);
scrollbar17.setVisible(true);
scrollbar18.setVisible(true);
scrollbar1.setVisible(true);
scrollbar20.setVisible(true);
scrollbar21.setVisible(true);
scrollbar22.setVisible(true);
scrollbar23.setVisible(true);
scrollbar24.setVisible(true);
jLabel4.setVisible(false);
}
else{
    jLabel4.setVisible(true);
scrollbar1.setVisible(false);
scrollbar2.setVisible(false);
scrollbar3.setVisible(false);
scrollbar4.setVisible(false);
scrollbar5.setVisible(false);
scrollbar6.setVisible(false);
scrollbar7.setVisible(false);
scrollbar8.setVisible(false);
scrollbar9.setVisible(false);
scrollbar10.setVisible(false);
scrollbar11.setVisible(false);
scrollbar12.setVisible(false);
scrollbar13.setVisible(false);
scrollbar14.setVisible(false);
scrollbar15.setVisible(false);
scrollbar16.setVisible(false);
scrollbar17.setVisible(false);
scrollbar18.setVisible(false);
scrollbar1.setVisible(false);
scrollbar20.setVisible(false);
scrollbar21.setVisible(false);
scrollbar22.setVisible(false);
scrollbar23.setVisible(false);
scrollbar24.setVisible(false);





}
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void TB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TB1ActionPerformed
boolean R=TB1.isSelected();
    if(R==true){
    jSlider3.setVisible(true);
    JL7.setVisible(false);
   TF1.setVisible(true);
 }
else{
    TF1.setVisible(false);
    jSlider3.setVisible(false);
    JL7.setVisible(true);
}        // TODO add your handling code here:
    }//GEN-LAST:event_TB1ActionPerformed

    private void TF2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF2ActionPerformed

    private void jSlider3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider3StateChanged
int a =jSlider3.getValue();
TF1.setText(String.valueOf(a));        // TODO add your handling code here:
    }//GEN-LAST:event_jSlider3StateChanged

    private void jSlider4StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider4StateChanged
int a =jSlider4.getValue();
TF2.setText(String.valueOf(a));        // TODO add your handling code here:
    }//GEN-LAST:event_jSlider4StateChanged

    private void jSlider5StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider5StateChanged
int a =jSlider5.getValue();
TF3.setText(String.valueOf(a));        // TODO add your handling code here:
    }//GEN-LAST:event_jSlider5StateChanged

    private void jSlider6StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider6StateChanged
int a =jSlider6.getValue();
TF4.setText(String.valueOf(a));        // TODO add your handling code here:
    }//GEN-LAST:event_jSlider6StateChanged

    private void jSlider7StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider7StateChanged
     int a =jSlider7.getValue();
TF5.setText(String.valueOf(a));    // TODO add your handling code here:
    }//GEN-LAST:event_jSlider7StateChanged

    private void jSlider8StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider8StateChanged
int a =jSlider8.getValue();
TF6.setText(String.valueOf(a));         // TODO add your handling code here:
    }//GEN-LAST:event_jSlider8StateChanged

    private void jSlider9StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider9StateChanged
int a =jSlider9.getValue();
TF7.setText(String.valueOf(a));         // TODO add your handling code here:
    }//GEN-LAST:event_jSlider9StateChanged

    private void jSlider10StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider10StateChanged
int a =jSlider10.getValue();
TF8.setText(String.valueOf(a));         // TODO add your handling code here:
    }//GEN-LAST:event_jSlider10StateChanged

    private void TB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TB2ActionPerformed
boolean R=TB2.isSelected();
    if(R==true){
    jSlider4.setVisible(true);
    JL8.setVisible(false);
   TF2.setVisible(true);
 }
else{
    TF2.setVisible(false);
    jSlider4.setVisible(false);
    JL8.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_TB2ActionPerformed
    }
    
    private void TB3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TB3ActionPerformed
        boolean R=TB3.isSelected();
    if(R==true){
    jSlider5.setVisible(true);
    JL9.setVisible(false);
   TF3.setVisible(true);
 }
else{
    TF3.setVisible(false);
    jSlider5.setVisible(false);
    JL9.setVisible(true);        // TODO add your handling code here:
    }// TODO add your handling code here:
    }//GEN-LAST:event_TB3ActionPerformed

    private void TB4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TB4ActionPerformed
        boolean R=TB4.isSelected();
    if(R==true){
    jSlider6.setVisible(true);
    JL10.setVisible(false);
   TF4.setVisible(true);
 }
else{
    TF4.setVisible(false);
    jSlider6.setVisible(false);
    JL10.setVisible(true);        // TODO add your handling code here:
    }        // TODO add your handling code here:
    }//GEN-LAST:event_TB4ActionPerformed

    private void TB5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TB5ActionPerformed
        boolean R=TB5.isSelected();
    if(R==true){
    jSlider7.setVisible(true);
    JL11.setVisible(false);
   TF5.setVisible(true);
 }
else{
    TF5.setVisible(false);
    jSlider7.setVisible(false);
    JL11.setVisible(true);        // TODO add your handling code here:
    }        // TODO add your handling code here:
    }//GEN-LAST:event_TB5ActionPerformed

    private void TB6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TB6ActionPerformed
        boolean R=TB6.isSelected();
    if(R==true){
    jSlider8.setVisible(true);
    JL12.setVisible(false);
   TF6.setVisible(true);
 }
else{
    TF6.setVisible(false);
    jSlider8.setVisible(false);
    JL12.setVisible(true);        // TODO add your handling code here:
    }        // TODO add your handling code here:
    }//GEN-LAST:event_TB6ActionPerformed

    private void TB7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TB7ActionPerformed
        boolean R=TB7.isSelected();
    if(R==true){
    jSlider9.setVisible(true);
    JL13.setVisible(false);
   TF7.setVisible(true);
 }
else{
    TF7.setVisible(false);
    jSlider9.setVisible(false);
    JL13.setVisible(true);        // TODO add your handling code here:
    }        // TODO add your handling code here:
    }//GEN-LAST:event_TB7ActionPerformed

    private void TB8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TB8ActionPerformed
             boolean R=TB8.isSelected();
    if(R==true){
    jSlider10.setVisible(true);
    JL14.setVisible(false);
   TF8.setVisible(true);
 }
else{
    TF8.setVisible(false);
    jSlider10.setVisible(false);
    JL14.setVisible(true);        // TODO add your handling code here:
    }   // TODO add your handling code here:
    }//GEN-LAST:event_TB8ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(submarine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(submarine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(submarine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(submarine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new submarine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB10;
    private javax.swing.JButton JB11;
    private javax.swing.JButton JB2;
    private javax.swing.JButton JB3;
    private javax.swing.JButton JB4;
    private javax.swing.JButton JB5;
    private javax.swing.JButton JB6;
    private javax.swing.JButton JB7;
    private javax.swing.JButton JB8;
    private javax.swing.JButton JB9;
    private javax.swing.JLabel JL10;
    private javax.swing.JLabel JL11;
    private javax.swing.JLabel JL12;
    private javax.swing.JLabel JL13;
    private javax.swing.JLabel JL14;
    private javax.swing.JLabel JL6;
    private javax.swing.JLabel JL7;
    private javax.swing.JLabel JL8;
    private javax.swing.JLabel JL9;
    private javax.swing.JToggleButton TB1;
    private javax.swing.JToggleButton TB2;
    private javax.swing.JToggleButton TB3;
    private javax.swing.JToggleButton TB4;
    private javax.swing.JToggleButton TB5;
    private javax.swing.JToggleButton TB6;
    private javax.swing.JToggleButton TB7;
    private javax.swing.JToggleButton TB8;
    private javax.swing.JTextField TF1;
    private javax.swing.JTextField TF2;
    private javax.swing.JTextField TF3;
    private javax.swing.JTextField TF4;
    private javax.swing.JTextField TF5;
    private javax.swing.JTextField TF6;
    private javax.swing.JTextField TF7;
    private javax.swing.JTextField TF8;
    private java.awt.Checkbox checkbox1;
    private java.awt.Checkbox checkbox2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JSlider jSlider10;
    private javax.swing.JSlider jSlider2;
    private javax.swing.JSlider jSlider3;
    private javax.swing.JSlider jSlider4;
    private javax.swing.JSlider jSlider5;
    private javax.swing.JSlider jSlider6;
    private javax.swing.JSlider jSlider7;
    private javax.swing.JSlider jSlider8;
    private javax.swing.JSlider jSlider9;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JTextArea jTextArea1;
    private java.awt.Scrollbar scrollbar1;
    private java.awt.Scrollbar scrollbar10;
    private java.awt.Scrollbar scrollbar11;
    private java.awt.Scrollbar scrollbar12;
    private java.awt.Scrollbar scrollbar13;
    private java.awt.Scrollbar scrollbar14;
    private java.awt.Scrollbar scrollbar15;
    private java.awt.Scrollbar scrollbar16;
    private java.awt.Scrollbar scrollbar17;
    private java.awt.Scrollbar scrollbar18;
    private java.awt.Scrollbar scrollbar2;
    private java.awt.Scrollbar scrollbar20;
    private java.awt.Scrollbar scrollbar21;
    private java.awt.Scrollbar scrollbar22;
    private java.awt.Scrollbar scrollbar23;
    private java.awt.Scrollbar scrollbar24;
    private java.awt.Scrollbar scrollbar3;
    private java.awt.Scrollbar scrollbar4;
    private java.awt.Scrollbar scrollbar5;
    private java.awt.Scrollbar scrollbar6;
    private java.awt.Scrollbar scrollbar7;
    private java.awt.Scrollbar scrollbar8;
    private java.awt.Scrollbar scrollbar9;
    private java.awt.TextField textField1;
    private java.awt.TextField textField2;
    private java.awt.TextField textField3;
    private java.awt.TextField textField4;
    // End of variables declaration//GEN-END:variables
}
