/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author macami-3
 */
public class tank extends javax.swing.JFrame {

    /**
     * Creates new form tank
     */
    public tank() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        B2 = new javax.swing.JButton();
        B3 = new javax.swing.JButton();
        B4 = new javax.swing.JButton();
        B5 = new javax.swing.JButton();
        B6 = new javax.swing.JButton();
        B7 = new javax.swing.JButton();
        B8 = new javax.swing.JButton();
        B9 = new javax.swing.JButton();
        R2 = new javax.swing.JRadioButton();
        R3 = new javax.swing.JRadioButton();
        R4 = new javax.swing.JRadioButton();
        R5 = new javax.swing.JRadioButton();
        R6 = new javax.swing.JRadioButton();
        R7 = new javax.swing.JRadioButton();
        R8 = new javax.swing.JRadioButton();
        R9 = new javax.swing.JRadioButton();
        L2 = new javax.swing.JLabel();
        L3 = new javax.swing.JLabel();
        L4 = new javax.swing.JLabel();
        L5 = new javax.swing.JLabel();
        L6 = new javax.swing.JLabel();
        L7 = new javax.swing.JLabel();
        L8 = new javax.swing.JLabel();
        L9 = new javax.swing.JLabel();
        jSlider1 = new javax.swing.JSlider();
        T1 = new javax.swing.JTextField();
        jSlider2 = new javax.swing.JSlider();
        T2 = new javax.swing.JTextField();
        jSlider3 = new javax.swing.JSlider();
        T3 = new javax.swing.JTextField();
        jSlider4 = new javax.swing.JSlider();
        T4 = new javax.swing.JTextField();
        jSlider5 = new javax.swing.JSlider();
        T5 = new javax.swing.JTextField();
        jSlider6 = new javax.swing.JSlider();
        T6 = new javax.swing.JTextField();
        jSlider7 = new javax.swing.JSlider();
        T7 = new javax.swing.JTextField();
        jSlider8 = new javax.swing.JSlider();
        T8 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        scrollbar1 = new java.awt.Scrollbar();
        scrollbar2 = new java.awt.Scrollbar();
        textField1 = new java.awt.TextField();
        textField2 = new java.awt.TextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jSpinner1 = new javax.swing.JSpinner();
        checkbox1 = new java.awt.Checkbox();
        JTB1 = new javax.swing.JToggleButton();
        JLB1 = new javax.swing.JLabel();
        JTB2 = new javax.swing.JToggleButton();
        JLB2 = new javax.swing.JLabel();
        JTB3 = new javax.swing.JToggleButton();
        JLB3 = new javax.swing.JLabel();
        JTB4 = new javax.swing.JToggleButton();
        JLB4 = new javax.swing.JLabel();
        JTB5 = new javax.swing.JToggleButton();
        JLB5 = new javax.swing.JLabel();
        JTB6 = new javax.swing.JToggleButton();
        JLB6 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        jLabel2.setBackground(new java.awt.Color(102, 102, 0));
        jLabel2.setForeground(new java.awt.Color(0, 153, 0));
        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(0, 0, 51));
        jTextField1.setFont(new java.awt.Font("Pagul", 1, 36)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setText("tank USA M60 Patton");
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 50));

        B2.setBackground(new java.awt.Color(0, 0, 51));
        B2.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        B2.setForeground(new java.awt.Color(255, 255, 255));
        B2.setText("R-P-M");
        B2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B2ActionPerformed(evt);
            }
        });
        getContentPane().add(B2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 110, -1));

        B3.setBackground(new java.awt.Color(0, 0, 51));
        B3.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        B3.setForeground(new java.awt.Color(255, 255, 255));
        B3.setText("TURBO");
        B3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B3ActionPerformed(evt);
            }
        });
        getContentPane().add(B3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, 110, -1));

        B4.setBackground(new java.awt.Color(0, 0, 51));
        B4.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        B4.setForeground(new java.awt.Color(255, 255, 255));
        B4.setText("A-P-S");
        B4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B4ActionPerformed(evt);
            }
        });
        getContentPane().add(B4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, 110, -1));

        B5.setBackground(new java.awt.Color(0, 0, 51));
        B5.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        B5.setForeground(new java.awt.Color(255, 255, 255));
        B5.setText("LIGHT");
        B5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5ActionPerformed(evt);
            }
        });
        getContentPane().add(B5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, 110, -1));

        B6.setBackground(new java.awt.Color(0, 0, 51));
        B6.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        B6.setForeground(new java.awt.Color(255, 255, 255));
        B6.setText("BEEM");
        B6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B6ActionPerformed(evt);
            }
        });
        getContentPane().add(B6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, 110, -1));

        B7.setBackground(new java.awt.Color(0, 0, 51));
        B7.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        B7.setForeground(new java.awt.Color(255, 255, 255));
        B7.setText("N-B-C");
        B7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B7ActionPerformed(evt);
            }
        });
        getContentPane().add(B7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 270, 110, -1));

        B8.setBackground(new java.awt.Color(0, 0, 51));
        B8.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        B8.setForeground(new java.awt.Color(255, 255, 255));
        B8.setText("S-G-L");
        B8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B8ActionPerformed(evt);
            }
        });
        getContentPane().add(B8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 310, 110, -1));

        B9.setBackground(new java.awt.Color(0, 0, 51));
        B9.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        B9.setForeground(new java.awt.Color(255, 255, 255));
        B9.setText("A-P-P");
        B9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B9ActionPerformed(evt);
            }
        });
        getContentPane().add(B9, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 350, 110, -1));

        R2.setBackground(new java.awt.Color(0, 0, 51));
        R2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R2ActionPerformed(evt);
            }
        });
        getContentPane().add(R2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 70, -1, -1));

        R3.setBackground(new java.awt.Color(0, 0, 51));
        R3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R3ActionPerformed(evt);
            }
        });
        getContentPane().add(R3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 110, -1, -1));

        R4.setBackground(new java.awt.Color(0, 0, 51));
        getContentPane().add(R4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 150, -1, -1));

        R5.setBackground(new java.awt.Color(0, 0, 51));
        getContentPane().add(R5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 190, -1, -1));

        R6.setBackground(new java.awt.Color(0, 0, 51));
        getContentPane().add(R6, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 230, -1, -1));

        R7.setBackground(new java.awt.Color(0, 0, 51));
        getContentPane().add(R7, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 270, -1, -1));

        R8.setBackground(new java.awt.Color(0, 0, 51));
        getContentPane().add(R8, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 310, -1, -1));

        R9.setBackground(new java.awt.Color(0, 0, 51));
        getContentPane().add(R9, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 350, -1, -1));

        L2.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        L2.setForeground(new java.awt.Color(255, 255, 255));
        L2.setText("OFF");
        getContentPane().add(L2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, 110, -1));

        L3.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        L3.setForeground(new java.awt.Color(255, 255, 255));
        L3.setText("OFF");
        getContentPane().add(L3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 110, 110, -1));

        L4.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        L4.setForeground(new java.awt.Color(255, 255, 255));
        L4.setText("DEACTIVE");
        getContentPane().add(L4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, 110, -1));

        L5.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        L5.setForeground(new java.awt.Color(255, 255, 255));
        L5.setText("OFF");
        getContentPane().add(L5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 190, 110, -1));

        L6.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        L6.setForeground(new java.awt.Color(255, 255, 255));
        L6.setText("OFF");
        getContentPane().add(L6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 230, 110, -1));

        L7.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        L7.setForeground(new java.awt.Color(255, 255, 255));
        L7.setText("OFF");
        getContentPane().add(L7, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 270, 110, -1));

        L8.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        L8.setForeground(new java.awt.Color(255, 255, 255));
        L8.setText("OFF");
        getContentPane().add(L8, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 310, 110, -1));

        L9.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        L9.setForeground(new java.awt.Color(255, 255, 255));
        L9.setText("OFF");
        getContentPane().add(L9, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 350, 110, -1));

        jSlider1.setBackground(new java.awt.Color(255, 255, 255));
        jSlider1.setForeground(new java.awt.Color(0, 0, 51));
        jSlider1.setValue(0);
        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider1StateChanged(evt);
            }
        });
        getContentPane().add(jSlider1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 190, -1, -1));

        T1.setBackground(new java.awt.Color(0, 0, 51));
        T1.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        T1.setForeground(new java.awt.Color(255, 255, 255));
        T1.setText("0");
        getContentPane().add(T1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 190, 80, -1));

        jSlider2.setBackground(new java.awt.Color(255, 255, 255));
        jSlider2.setForeground(new java.awt.Color(0, 0, 51));
        jSlider2.setValue(0);
        jSlider2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider2StateChanged(evt);
            }
        });
        getContentPane().add(jSlider2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 70, -1, -1));

        T2.setBackground(new java.awt.Color(0, 0, 51));
        T2.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        T2.setForeground(new java.awt.Color(255, 255, 255));
        T2.setText("0");
        getContentPane().add(T2, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 70, 80, -1));

        jSlider3.setBackground(new java.awt.Color(255, 255, 255));
        jSlider3.setForeground(new java.awt.Color(0, 0, 51));
        jSlider3.setValue(0);
        jSlider3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider3StateChanged(evt);
            }
        });
        getContentPane().add(jSlider3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 110, -1, -1));

        T3.setBackground(new java.awt.Color(0, 0, 51));
        T3.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        T3.setForeground(new java.awt.Color(255, 255, 255));
        T3.setText("0");
        getContentPane().add(T3, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 110, 80, -1));

        jSlider4.setBackground(new java.awt.Color(255, 255, 255));
        jSlider4.setForeground(new java.awt.Color(0, 0, 51));
        jSlider4.setValue(0);
        jSlider4.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider4StateChanged(evt);
            }
        });
        getContentPane().add(jSlider4, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 150, -1, -1));

        T4.setBackground(new java.awt.Color(0, 0, 51));
        T4.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        T4.setForeground(new java.awt.Color(255, 255, 255));
        T4.setText("0");
        T4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T4ActionPerformed(evt);
            }
        });
        getContentPane().add(T4, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 150, 80, -1));

        jSlider5.setBackground(new java.awt.Color(255, 255, 255));
        jSlider5.setForeground(new java.awt.Color(0, 0, 51));
        jSlider5.setToolTipText("");
        jSlider5.setValue(0);
        jSlider5.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider5StateChanged(evt);
            }
        });
        getContentPane().add(jSlider5, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 230, -1, -1));

        T5.setBackground(new java.awt.Color(0, 0, 51));
        T5.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        T5.setForeground(new java.awt.Color(255, 255, 255));
        T5.setText("0");
        T5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T5ActionPerformed(evt);
            }
        });
        getContentPane().add(T5, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 230, 80, -1));

        jSlider6.setBackground(new java.awt.Color(255, 255, 255));
        jSlider6.setForeground(new java.awt.Color(0, 0, 51));
        jSlider6.setValue(0);
        jSlider6.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider6StateChanged(evt);
            }
        });
        getContentPane().add(jSlider6, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 270, -1, -1));

        T6.setBackground(new java.awt.Color(0, 0, 51));
        T6.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        T6.setForeground(new java.awt.Color(255, 255, 255));
        T6.setText("0");
        getContentPane().add(T6, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 270, 80, -1));

        jSlider7.setBackground(new java.awt.Color(255, 255, 255));
        jSlider7.setForeground(new java.awt.Color(0, 0, 51));
        jSlider7.setValue(0);
        jSlider7.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider7StateChanged(evt);
            }
        });
        getContentPane().add(jSlider7, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 310, -1, -1));

        T7.setBackground(new java.awt.Color(0, 0, 51));
        T7.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        T7.setForeground(new java.awt.Color(255, 255, 255));
        T7.setText("0");
        getContentPane().add(T7, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 310, 80, -1));

        jSlider8.setBackground(new java.awt.Color(255, 255, 255));
        jSlider8.setForeground(new java.awt.Color(0, 0, 51));
        jSlider8.setValue(0);
        jSlider8.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider8StateChanged(evt);
            }
        });
        getContentPane().add(jSlider8, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 350, -1, -1));

        T8.setBackground(new java.awt.Color(0, 0, 51));
        T8.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        T8.setForeground(new java.awt.Color(255, 255, 255));
        T8.setText("0");
        getContentPane().add(T8, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 350, 80, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("SOLDIER COUNT");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("AMMO COUNT");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, -1, -1));

        scrollbar1.setBackground(new java.awt.Color(0, 0, 51));
        scrollbar1.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(scrollbar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 10, -1, -1));

        scrollbar2.setBackground(new java.awt.Color(0, 0, 51));
        scrollbar2.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(scrollbar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, -1, -1));

        textField1.setBackground(new java.awt.Color(0, 0, 51));
        textField1.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(textField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 390, 530, 50));

        textField2.setBackground(new java.awt.Color(0, 0, 51));
        textField2.setForeground(new java.awt.Color(255, 255, 255));
        textField2.setText("TYPE MSSEG");
        getContentPane().add(textField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 450, 390, -1));

        jButton1.setBackground(new java.awt.Color(0, 0, 51));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("SEND");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(823, 450, 100, -1));

        jButton2.setBackground(new java.awt.Color(0, 0, 51));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("ROKECT");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 110, -1));

        jButton3.setBackground(new java.awt.Color(0, 0, 51));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("REDAR");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, -1, -1));

        jButton4.setBackground(new java.awt.Color(0, 0, 51));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("MISSLE");
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 80, -1));

        jButton5.setBackground(new java.awt.Color(0, 0, 51));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("SHOOT");
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, -1, -1));

        jButton6.setBackground(new java.awt.Color(0, 0, 51));
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("MAIN CANON");
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 110, -1));

        jButton7.setBackground(new java.awt.Color(0, 0, 51));
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("L-M-G");
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 80, -1));

        jButton8.setBackground(new java.awt.Color(0, 0, 51));
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("CANON");
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, -1, -1));

        jButton9.setBackground(new java.awt.Color(0, 0, 51));
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("ROTAE");
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 110, -1));

        jButton10.setBackground(new java.awt.Color(0, 0, 51));
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("BOMBS");
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, -1, -1));

        jButton11.setBackground(new java.awt.Color(0, 0, 51));
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setText("A D P S");
        getContentPane().add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, -1, -1));

        jButton12.setBackground(new java.awt.Color(0, 0, 51));
        jButton12.setForeground(new java.awt.Color(255, 255, 255));
        jButton12.setText("M85");
        getContentPane().add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 80, -1));

        jButton13.setBackground(new java.awt.Color(0, 0, 51));
        jButton13.setForeground(new java.awt.Color(255, 255, 255));
        jButton13.setText("105 mm");
        getContentPane().add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, -1, -1));
        getContentPane().add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 20, -1, 30));

        checkbox1.setBackground(new java.awt.Color(0, 0, 51));
        checkbox1.setForeground(new java.awt.Color(255, 255, 255));
        checkbox1.setLabel("AREA CLEAR");
        getContentPane().add(checkbox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, -1, -1));

        JTB1.setBackground(new java.awt.Color(0, 0, 51));
        JTB1.setFont(new java.awt.Font("Liberation Serif", 1, 15)); // NOI18N
        JTB1.setForeground(new java.awt.Color(255, 255, 255));
        JTB1.setText("ENGINE");
        JTB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTB1ActionPerformed(evt);
            }
        });
        getContentPane().add(JTB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 130, -1));

        JLB1.setFont(new java.awt.Font("Manjari", 1, 15)); // NOI18N
        JLB1.setForeground(new java.awt.Color(255, 255, 255));
        JLB1.setText("ENGINE:OFF");
        getContentPane().add(JLB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 90, 20));

        JTB2.setBackground(new java.awt.Color(0, 0, 51));
        JTB2.setFont(new java.awt.Font("Liberation Serif", 1, 15)); // NOI18N
        JTB2.setForeground(new java.awt.Color(255, 255, 255));
        JTB2.setText("TARCKTION");
        JTB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTB2ActionPerformed(evt);
            }
        });
        getContentPane().add(JTB2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 130, -1));

        JLB2.setFont(new java.awt.Font("Manjari", 1, 15)); // NOI18N
        JLB2.setForeground(new java.awt.Color(255, 255, 255));
        JLB2.setText("OFF");
        getContentPane().add(JLB2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 90, 20));

        JTB3.setBackground(new java.awt.Color(0, 0, 51));
        JTB3.setFont(new java.awt.Font("Liberation Serif", 1, 15)); // NOI18N
        JTB3.setForeground(new java.awt.Color(255, 255, 255));
        JTB3.setText("GPS");
        JTB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTB3ActionPerformed(evt);
            }
        });
        getContentPane().add(JTB3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 130, -1));

        JLB3.setFont(new java.awt.Font("Manjari", 1, 15)); // NOI18N
        JLB3.setForeground(new java.awt.Color(255, 255, 255));
        JLB3.setText("OFF");
        getContentPane().add(JLB3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 90, 20));

        JTB4.setBackground(new java.awt.Color(0, 0, 51));
        JTB4.setFont(new java.awt.Font("Liberation Serif", 1, 15)); // NOI18N
        JTB4.setForeground(new java.awt.Color(255, 255, 255));
        JTB4.setText("SATALIGHT");
        JTB4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTB4ActionPerformed(evt);
            }
        });
        getContentPane().add(JTB4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 130, -1));

        JLB4.setFont(new java.awt.Font("Manjari", 1, 15)); // NOI18N
        JLB4.setForeground(new java.awt.Color(255, 255, 255));
        JLB4.setText("OFF");
        getContentPane().add(JLB4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 90, 20));

        JTB5.setBackground(new java.awt.Color(0, 0, 51));
        JTB5.setFont(new java.awt.Font("Liberation Serif", 1, 15)); // NOI18N
        JTB5.setForeground(new java.awt.Color(255, 255, 255));
        JTB5.setText("W-I-F-I-7");
        JTB5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTB5ActionPerformed(evt);
            }
        });
        getContentPane().add(JTB5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 130, -1));

        JLB5.setFont(new java.awt.Font("Manjari", 1, 15)); // NOI18N
        JLB5.setForeground(new java.awt.Color(255, 255, 255));
        JLB5.setText("OFF");
        getContentPane().add(JLB5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, 90, 20));

        JTB6.setBackground(new java.awt.Color(0, 0, 51));
        JTB6.setFont(new java.awt.Font("Liberation Serif", 1, 15)); // NOI18N
        JTB6.setForeground(new java.awt.Color(255, 255, 255));
        JTB6.setText("A-B-S");
        JTB6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTB6ActionPerformed(evt);
            }
        });
        getContentPane().add(JTB6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 130, -1));

        JLB6.setFont(new java.awt.Font("Manjari", 1, 15)); // NOI18N
        JLB6.setForeground(new java.awt.Color(255, 255, 255));
        JLB6.setText("OFF");
        getContentPane().add(JLB6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, 90, 20));

        jLabel6.setIcon(new javax.swing.ImageIcon("/home/macami-3/NetBeansProjects/slarmy/tank-16m4grmxq22z6mao.jpg")); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-210, -310, -1, -1));

        getAccessibleContext().setAccessibleName("tank");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B8ActionPerformed
boolean B1 = R8.isSelected();
    if (B1==true){
    L8.setText(" ON");
    jSlider7.setVisible(true);
    T7.setVisible(true);
    }
    else{
    L8.setText(" OFF");
    jSlider7.setVisible(false);
    T7.setVisible(false);
    }        // TODO add your handling code here:
    }//GEN-LAST:event_B8ActionPerformed

    private void R2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R2ActionPerformed

    }//GEN-LAST:event_R2ActionPerformed

    private void B3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B3ActionPerformed
boolean B1 = R2.isSelected();
    if (B1==true){
    L2.setText("ON SPEED");
    jSlider2.setVisible(true);
    T2.setVisible(true);
    }
    else{
    L2.setText("OFF");
    jSlider2.setVisible(false);
    T2.setVisible(false);
    }       // TODO add your handling code here:
    }//GEN-LAST:event_B3ActionPerformed

    private void B2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B2ActionPerformed
boolean B1 = R3.isSelected();
    if (B1==true){
    L3.setText("ON SPEED");
    jSlider3.setVisible(true);
    T3.setVisible(true);
    }
    else{
    L3.setText(" OFF");
    jSlider3.setVisible(false);
    T3.setVisible(false);
    }
            // TODO add your handling code here:
    }//GEN-LAST:event_B2ActionPerformed

    private void R3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R3ActionPerformed

    private void jSlider2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider2StateChanged
int a =jSlider2.getValue();
T2.setText(String.valueOf(a));        // TODO add your handling code here:
    }//GEN-LAST:event_jSlider2StateChanged

    private void jSlider3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider3StateChanged
    int a =jSlider3.getValue();
T3.setText(String.valueOf(a));        // TODO add your handling code here:
    }//GEN-LAST:event_jSlider3StateChanged

    private void T4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T4ActionPerformed

    private void T5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T5ActionPerformed

    private void B4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B4ActionPerformed
    boolean B = R4.isSelected();
    if (B==true){
    L4.setText("ACTIVE");
    jSlider4.setVisible(true);
    T4.setVisible(true);
    }
    else{
    L4.setText("DEACTIVE");
    jSlider4.setVisible(false);
    T4.setVisible(false);
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_B4ActionPerformed

    private void jSlider4StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider4StateChanged
        int a =jSlider4.getValue();
T4.setText(String.valueOf(a));     // TODO add your handling code here:
    }//GEN-LAST:event_jSlider4StateChanged

    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider1StateChanged
 int a =jSlider1.getValue();
T1.setText(String.valueOf(a));         // TODO add your handling code here:
    }//GEN-LAST:event_jSlider1StateChanged

    private void B5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5ActionPerformed
boolean B1 = R5.isSelected();
    if (B1==true){
    L5.setText(" ON");
    jSlider1.setVisible(true);
    T1.setVisible(true);
    }
    else{
    L5.setText(" OFF");
    jSlider1.setVisible(false);
    T1.setVisible(false);
    }        // TODO add your handling code here:
    }//GEN-LAST:event_B5ActionPerformed

    private void jSlider5StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider5StateChanged
   int a =jSlider5.getValue();
T5.setText(String.valueOf(a));         // TODO add your handling code here:
    }//GEN-LAST:event_jSlider5StateChanged

    private void B6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B6ActionPerformed
boolean B1 = R6.isSelected();
    if (B1==true){
    L6.setText(" ON");
    jSlider5.setVisible(true);
    T5.setVisible(true);
    }
    else{
    L6.setText(" OFF");
    jSlider5.setVisible(false);
    T5.setVisible(false);
    }        // TODO add your handling code here:
    }//GEN-LAST:event_B6ActionPerformed

    private void jSlider6StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider6StateChanged
    int a =jSlider6.getValue();
T6.setText(String.valueOf(a));         // TODO add your handling code here:
    }//GEN-LAST:event_jSlider6StateChanged

    private void B7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B7ActionPerformed
boolean B1 = R7.isSelected();
    if (B1==true){
    L7.setText(" ON");
    jSlider6.setVisible(true);
    T6.setVisible(true);
    }
    else{
    L2.setText(" OFF");
    jSlider6.setVisible(false);
    T6.setVisible(false);
    }        // TODO add your handling code here:
    }//GEN-LAST:event_B7ActionPerformed

    private void jSlider7StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider7StateChanged
    int a =jSlider7.getValue();
T7.setText(String.valueOf(a));         // TODO add your handling code here:
    }//GEN-LAST:event_jSlider7StateChanged

    private void jSlider8StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider8StateChanged
    int a =jSlider8.getValue();
T8.setText(String.valueOf(a));         // TODO add your handling code here:
    }//GEN-LAST:event_jSlider8StateChanged

    private void B9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B9ActionPerformed
boolean B1 = R9.isSelected();
    if (B1==true){
    L9.setText(" ON");
    jSlider8.setVisible(true);
    T8.setVisible(true);
    }
    else{
    L9.setText(" OFF");
    jSlider8.setVisible(false);
    T8.setVisible(false);
    }
            // TODO add your handling code here:
    }//GEN-LAST:event_B9ActionPerformed

    private void JTB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTB1ActionPerformed
if(JTB1.isSelected()){
    JLB1.setText("ENGINE:ON");
}
else{
    JLB1.setText("ENGINE:OFF");
}        // TODO add your handling code here:
    }//GEN-LAST:event_JTB1ActionPerformed

    private void JTB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTB2ActionPerformed
if(JTB2.isSelected()){
    JLB2.setText("ON");
}
else{
    JLB2.setText("OFF");
}         // TODO add your handling code here:
    }//GEN-LAST:event_JTB2ActionPerformed

    private void JTB3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTB3ActionPerformed
if(JTB3.isSelected()){
    JLB3.setText("ON");
}
else{
    JLB3.setText("OFF");
}         // TODO add your handling code here:
    }//GEN-LAST:event_JTB3ActionPerformed

    private void JTB4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTB4ActionPerformed
if(JTB4.isSelected()){
    JLB4.setText("ON");
}
else{
    JLB4.setText("OFF");
}         // TODO add your handling code here:
    }//GEN-LAST:event_JTB4ActionPerformed

    private void JTB5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTB5ActionPerformed
if(JTB5.isSelected()){
    JLB5.setText("ON");
}
else{
    JLB5.setText("OFF");
}         // TODO add your handling code here:
    }//GEN-LAST:event_JTB5ActionPerformed

    private void JTB6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTB6ActionPerformed
if(JTB6.isSelected()){
    JLB6.setText("ON");
}
else{
    JLB6.setText("OFF");
}         // TODO add your handling code here:
    }//GEN-LAST:event_JTB6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
textField2.setText("MESSEG SENDING ");         // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tank().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B2;
    private javax.swing.JButton B3;
    private javax.swing.JButton B4;
    private javax.swing.JButton B5;
    private javax.swing.JButton B6;
    private javax.swing.JButton B7;
    private javax.swing.JButton B8;
    private javax.swing.JButton B9;
    private javax.swing.JLabel JLB1;
    private javax.swing.JLabel JLB2;
    private javax.swing.JLabel JLB3;
    private javax.swing.JLabel JLB4;
    private javax.swing.JLabel JLB5;
    private javax.swing.JLabel JLB6;
    private javax.swing.JToggleButton JTB1;
    private javax.swing.JToggleButton JTB2;
    private javax.swing.JToggleButton JTB3;
    private javax.swing.JToggleButton JTB4;
    private javax.swing.JToggleButton JTB5;
    private javax.swing.JToggleButton JTB6;
    private javax.swing.JLabel L2;
    private javax.swing.JLabel L3;
    private javax.swing.JLabel L4;
    private javax.swing.JLabel L5;
    private javax.swing.JLabel L6;
    private javax.swing.JLabel L7;
    private javax.swing.JLabel L8;
    private javax.swing.JLabel L9;
    private javax.swing.JRadioButton R2;
    private javax.swing.JRadioButton R3;
    private javax.swing.JRadioButton R4;
    private javax.swing.JRadioButton R5;
    private javax.swing.JRadioButton R6;
    private javax.swing.JRadioButton R7;
    private javax.swing.JRadioButton R8;
    private javax.swing.JRadioButton R9;
    private javax.swing.JTextField T1;
    private javax.swing.JTextField T2;
    private javax.swing.JTextField T3;
    private javax.swing.JTextField T4;
    private javax.swing.JTextField T5;
    private javax.swing.JTextField T6;
    private javax.swing.JTextField T7;
    private javax.swing.JTextField T8;
    private java.awt.Checkbox checkbox1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JSlider jSlider2;
    private javax.swing.JSlider jSlider3;
    private javax.swing.JSlider jSlider4;
    private javax.swing.JSlider jSlider5;
    private javax.swing.JSlider jSlider6;
    private javax.swing.JSlider jSlider7;
    private javax.swing.JSlider jSlider8;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField jTextField1;
    private java.awt.Scrollbar scrollbar1;
    private java.awt.Scrollbar scrollbar2;
    private java.awt.TextField textField1;
    private java.awt.TextField textField2;
    // End of variables declaration//GEN-END:variables
}
